### PR TITLE
afterDeserialize phase that runs after deserialization of every resource

### PR DESCRIPTION
**Pull request by odedniv**

### CODE REVIEW

**Comment by tpodom** [comment]
LGTM, thanks!

**Comment by odedniv** [comment]
Actually just realized I forgot to update README :s (btw I pushed a tiny commit a second before you merged)

**Comment by tpodom** [comment]
No worries, I updated the readme. The change was to remove the unused self?

**Comment by odedniv** [comment]
Yup. Cool thanks!

**Pull request merged**
