### PR TITLE
Prevent snapshots from persisting.

### PR DESCRIPTION
**Pull request by jnfeinstein**

### CODE REVIEW

**Comment by jnfeinstein** [comment]
@tpodom can you take a look?

**Comment by tpodom** [comment]
@jnfeinstein I want to take a second look at the snapshot extension.  I think we could just explicitly exclude $snapshot to avoid breaking use of the $snapshots variable.

**Comment by jnfeinstein** [comment]
Sure.  You can scrub it from the data using the `beforeRequestWrapping` interceptor.  I coded that initially and discovered the discrepancy in `toJson` while testing.  My test case passed with and without the fix when testing against angular 1.2 and failed against 1.3+.

Philosophically, I would not be concerned with this as a breaking change.  It's coded as an internal API (using `$` as a prefix).  It will also be straightforward to find instances of this variable to update to the newer version, `$snapshots` is fairly unique.

What's the use case for operating on the internal `$snapshots` variable directly?

**Comment by tpodom** [comment]
I agree, I don't see any particular harm in renaming it.

**Pull request merged**
