### PR TITLE
support polymorphic association serialization

### PR DESCRIPTION
**Pull request by odedniv**
- rename confusing data arguments to result for consistency

I think this solves #195

### CODE REVIEW

**Comment by tpodom** [comment]
LGTM

**Comment by odedniv** [comment]
It doesn't really support different serialize/deserialize attribute names, can you suggest the best course of action to support that?

(I don't need it myself)

**Comment by tpodom** [comment]
I’m not sure. What’s an example? We don’t use polymorphic associations so I’m not too familiar with how they would work.

**Comment by odedniv** [comment]
Polymorphic associations are implemented with two columns: `<association>_id` and `<association>_type`. For example, a `Comment` model that can associated to different models:

```ruby
class Comment
  belongs_to :commentable, polymorphic: true
end
```

Would have a `commentable_type` and `commentable_id`. When a `commentable` is assigned (in Ruby) Rails automatically sets `commentable_type`, and when `comment.commentable` is called it automatically loads the appropriate model.

I think one of the features here is to convert `commentable_type` and `commentable_id` to `commentableType` and `commentableId`. I don't use this feature, but I thought this PR could break it.

**Pull request merged**
